### ISSUE TITLE
Version 1: MVP

### ISSUE THREAD

**Issue by zakiego** [meratusdev/act-elgharantaly#1]
# Layout
- [x] Fix title
- [ ] Add og image

# Page
- [x] Pagination Page
    - [x] Adjust mobile font
- Post Page
    - [x] Adjust text
- [x] Search Page

# Function
- [x] Sort by date

# Feature
- [x] Next and prev post recommendation
